// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-5_JUdoYE86l3dxtXbURrzx4Hv_FBGSQ',
    appId: '1:178369608870:web:1659239e81f0dcdf1a0867',
    messagingSenderId: '178369608870',
    projectId: 'database-3523d',
    authDomain: 'database-3523d.firebaseapp.com',
    storageBucket: 'database-3523d.appspot.com',
    measurementId: 'G-GEC87W1LQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmaCCi0A-p_Iso5HSd85nBNx-DWrQ43QM',
    appId: '1:178369608870:android:3fe35d795551b23f1a0867',
    messagingSenderId: '178369608870',
    projectId: 'database-3523d',
    storageBucket: 'database-3523d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPEji83yJG-zmM2J84eIeQvUBzJRjVkRo',
    appId: '1:178369608870:ios:e023fffd8cc62db51a0867',
    messagingSenderId: '178369608870',
    projectId: 'database-3523d',
    storageBucket: 'database-3523d.appspot.com',
    iosBundleId: 'com.example.villageVoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPEji83yJG-zmM2J84eIeQvUBzJRjVkRo',
    appId: '1:178369608870:ios:e023fffd8cc62db51a0867',
    messagingSenderId: '178369608870',
    projectId: 'database-3523d',
    storageBucket: 'database-3523d.appspot.com',
    iosBundleId: 'com.example.villageVoice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-5_JUdoYE86l3dxtXbURrzx4Hv_FBGSQ',
    appId: '1:178369608870:web:ffda40d92082a8891a0867',
    messagingSenderId: '178369608870',
    projectId: 'database-3523d',
    authDomain: 'database-3523d.firebaseapp.com',
    storageBucket: 'database-3523d.appspot.com',
    measurementId: 'G-S9J522E1W5',
  );
}
